image: gitpod/workspace-java-21

vscode:
    extensions:
        - vscjava.vscode-java-pack
        - pleiades.java-extension-pack-jdk
        - formulahendry.code-runner

tasks:
  - name: Install shellcheck
    init: |
      echo "📦 Installing shellcheck..."
      sudo apt install shellcheck
      echo "✅ shellcheck installed"
  - name: Install direnv
    init: |
      echo "📦 Installing direnv..."
      curl -sfL https://direnv.net/sHELL  | bash
      echo "✅ direnv installed"

  - name: Setup direnv hook for bash
    init: |
      echo "🔌 Adding direnv hook to ~/.bashrc..."
      echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
      source ~/.bashrc
      echo "✅ direnv hook added and sourced"
  - name: List Java Env
    init: |
      echo "📦 Listing Java Env..."
      sdk current

  